- src: https://github.com/bphinney/ansible-oracle-jdk

- src: https://nexus.ncrsmb.com/momentum-ansible/momentum/ansible-cassandra-backup/1.1/ansible-cassandra-backup-1.1.tar.gz

#- src: https://github.com/malk/ansible-java8-oracle
