---
- hosts: cassandra_seed
  become: yes
  gather_facts: yes
  vars:
    cassandra_listen_interface: eth0
    cassandra_seed_list: "{{ groups['cassandra_seed'] | map('extract', hostvars, ['ansible_' + cassandra_listen_interface, 'ipv4', 'address']) | list }}"
    cassandra_data_dirs: [/data/cassandra/data]
    cassandra_commit_log_dir: /data/cassandra/commitlog
    cassandra_saved_caches_dir: /data/cassandra/saved_caches
    cassandra_hints_dir: /data/cassandra/hints
  roles:
    - ansible-oracle-jdk
    #- ansible-java8-oracle
    - ansible-cassandra
    - ansible-cassandra-backup

- hosts: cassandra:!cassandra_seed
  become: yes
  gather_facts: yes
  serial: 1
  vars:
    cassandra_listen_interface: eth0
    cassandra_seed_list: "{{ groups['cassandra_seed'] | map('extract', hostvars, ['ansible_' + cassandra_listen_interface, 'ipv4', 'address']) | list }}"
    cassandra_data_dirs: [/data/cassandra/data]
    cassandra_commit_log_dir: /data/cassandra/commitlog
    cassandra_saved_caches_dir: /data/cassandra/saved_caches
    cassandra_hints_dir: /data/cassandra/hints
  roles:
    - ansible-oracle-jdk
    #- ansible-java8-oracle
    - ansible-cassandra
    - ansible-cassandra-backup
