- name: Create cassandra group
  group:
    name: "{{ cassandra_group }}"
    state: present
    system: yes
  register: cassandra_group_created
  become: true

- name: Create cassandra user
  user:
    home: "/home/{{ cassandra_user }}"
    name: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    system: yes
  when: cassandra_group_created|changed
  become: true

- name: Download tarball
  local_action: get_url url="{{ cassandra_download_url }}" dest="{{ cassandra_staging_dir }}/{{ cassandra_archive }}"
  become: False
  run_once: True
  become: true

- name: Copy tarball
  copy:
    src: "{{ cassandra_staging_dir }}/{{ cassandra_archive }}"
    dest: "{{ cassandra_install_dir }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: 0700
  become: true

- name: Unpack
  unarchive:
    src: "{{ cassandra_staging_dir }}/{{ cassandra_archive }}"
    dest: "{{ cassandra_install_dir }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: 0700
  become: true

- name: Symlink to current version
  file:
    state: link
    src: "{{ cassandra_real_home }}"
    dest: "{{ cassandra_home }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
  become: true

- name: Add cassandra to PATH
  template:
    src: cassandra.sh.j2
    dest: /etc/profile.d/cassadra.sh
    mode: 0644
    owner: root
    group: root
  become: true

- name: Create cassandra directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: 0755
  with_items:
    - "{{ cassandra_commit_log_dir }}"
    - "{{ cassandra_saved_caches_dir }}"
    - "{{ cassandra_log_dir }}"
  become: true

- name: Create cassandra data directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: 0755
  with_items: "{{ cassandra_data_dirs }}"
  become: true
