---
- name: reload systemd
  become: True
  command: systemctl daemon-reload

- name: restart cassandra
  action: service name=cassandra state=restarted enabled=yes
  when: cassandra_restart_on_change|default(False) and cassandra_started|changed
